openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: 'Scot Stroman'
                  email: iwilkinson@example.com
                  email_verified_at: '2023-03-04T06:59:15.000000Z'
                  created_at: '2023-03-04T06:59:15.000000Z'
                  updated_at: '2023-03-04T06:59:15.000000Z'
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 'Scot Stroman'
                  email:
                    type: string
                    example: iwilkinson@example.com
                  email_verified_at:
                    type: string
                    example: '2023-03-04T06:59:15.000000Z'
                  created_at:
                    type: string
                    example: '2023-03-04T06:59:15.000000Z'
                  updated_at:
                    type: string
                    example: '2023-03-04T06:59:15.000000Z'
      tags:
        - Endpoints
  /api/health-check:
    get:
      summary: ''
      operationId: getApiHealthCheck
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: up
                  services:
                    database: up
                    redis: up
                properties:
                  status:
                    type: string
                    example: up
                  services:
                    type: object
                    properties:
                      database:
                        type: string
                        example: up
                      redis:
                        type: string
                        example: up
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
