# github action that checks code with Rector
name: Rector

on:
  push:
    paths:
      - "app/**"
      - "database/**"
      - "routes/**"
      - "tests/**"
  pull_request:
    paths:
      - "app/**"
      - "database/**"
      - "routes/**"
      - "tests/**"

jobs:
  rector:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == 'alphaolomi/laravel-api-docs'
    steps:
      - if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v3
        with:
          # Must be used to trigger workflow after push
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: "ramsey/composer-install@v2"

      - run: vendor/bin/rector --ansi

      # If pull request, commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event_name == 'pull_request'
        with:
          commit_message: "[rector] Rector fixes"

      # If push, create pull request
      - uses: peter-evans/create-pull-request@v3
        if: github.event_name == 'push'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[rector] Rector fixes"
          labels: "rector"
          assignees: "alphaolomi"
          title: "[rector] Rector fixes"
          body: |
            This PR is auto-generated by rector
