# github action that checks code with Rector
name: Rector

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    paths:
      - "app/**"
      - "database/**"
      - "routes/**"
      - "tests/**"
  pull_request:
    paths:
      - "app/**"
      - "database/**"
      - "routes/**"
      - "tests/**"

jobs:
  rector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: "ramsey/composer-install@v3"

      - run: vendor/bin/rector --ansi

      # If pull request, commit changes
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event_name == 'pull_request'
        with:
          commit_message: "[rector] Rector fixes"

      # If push, create pull request
      - uses: peter-evans/create-pull-request@v6
        if: github.event_name == 'push' || (github.event_name == 'schedule')
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: "[rector] Rector fixes"
          branch: "rector-fixes"
          labels: "rector"
          assignees: "alphaolomi"
          title: "chore: Rector fixes"
          body: |
            This PR is auto-generated by [Rector Action](https://github.com/alphaolomi/laravel-api-docs/actions/workflows/rector.yaml)
            See [commit](${{ github.workflow.url }}/runs/${{ github.run_id}})
