# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Check for stale issues and pull requests
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been inactive for a while. If it's no longer relevant, please let us know and we'll close it. Otherwise, feel free to provide any updates or additional information. Thank you!
          stale-pr-message: |
            This pull request has been inactive for a while. If it's no longer needed or if there are unresolved issues, please let us know and we'll close it. Otherwise, feel free to provide any updates or address any feedback. Thank you!
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          days-before-stale: 30
          days-before-close: 7
          only: issues, pull-requests
